[project]
name = "lang-factory"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Serhii Rumiantsev", email = "grey.rsm@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langgraph>=1.2.12",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "langgraph-cli[inmem]>=0.4.32",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]

[project.scripts]
lang-factory = "lang_factory:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
